'use strict';
(()=>{
const q=new URLSearchParams(location.search), missionId=q.get('mode')||'hellevator-shaft', routes={'hellevator-shaft':'pac-maze','district9-wall-breaker':'mario-platform','miroh-maze-runner':'snake-grid','yellow-wood-stealth':'cheese-dreams','gods-menu-rush':'dino-run','back-door-dash':'ball-block','shadow-forest-hunt':'cat-drop','quantum-dimension-switcher':'hop-run','chk-chk-target-rush':'ate-maze'}, id=routes[missionId]||missionId, member=q.get('char')||'bangchan', C=document.querySelector('#scene'), c=C.getContext('2d'), W=960,H=600, $=s=>document.querySelector(s), keys=new Set();
c.imageSmoothingEnabled=false;
const MODES={
 'pac-maze':{title:'DATA MAZE · PAC RUN',art:'world1',bg:'scene-miroh.webp',help:'Arrow keys / WASD move. Collect every data dot; avoid the roaming glitches.',theme:'#4cf5e9'},
 'mario-platform':{title:'PIPELINE PLATFORMER',art:'world1',bg:'scene-hellevator.webp',help:'A/D move · Space or ↑ jumps. Collect 8 memory sparks and reach the exit.',theme:'#ffce58'},
 'snake-grid':{title:'SNAKE COOL · NEON CIRCUIT',art:'world1',bg:'scene-thisthat.webp',help:'Arrow keys steer. Eat 8 energy cells. Avoid the wall and your own tail.',theme:'#73ff91'},
 'cheese-dreams':{title:'CHEESE DREAMS · MOON BOUNCE',art:'world2',bg:'scene-godsmenu.webp',help:'A/D steer the bouncing cheese. Land on spring pads and gather 6 moon cheeses.',theme:'#ffb63d'},
 'dino-run':{title:'DINO RUN · OUTRUN THE GLITCH',art:'world2',bg:'scene-rockstar.webp',help:'Space / ↑ jumps. Survive the signal storm and clear 8 obstacles.',theme:'#d8e6e8'},
 'ball-block':{title:'BALL VS BLOCK · FIREWALL BREAK',art:'world2',bg:'scene-district9.webp',help:'Click/tap a direction to fire. Break 12 numbered firewall blocks before they reach you.',theme:'#4fd8ff'},
 'cat-drop':{title:'CAT DROP · MEMBER MERGE',art:'world3',bg:'scene-winter.webp',help:'Move with A/D and drop with Space. Merge matching pixel cats; build a 4-cat crown.',theme:'#ff94ca'},
 'hop-run':{title:'HOP · WATERWAY RUN',art:'hop',bg:'scene-hop.webp',help:'A/D move · Space jumps. Cross the waterway, dodge crates, and collect 7 light orbs.',theme:'#58e5ff'},
 'ate-maze':{title:'ATE · BREAD RUN MAZE',art:'ate',bg:'scene-ate.webp',help:'Arrow keys / WASD explore. Find 3 keycards, then reach the extraction gate.',theme:'#ff5f72'}
};
const M=MODES[id]||MODES['pac-maze']; document.documentElement.style.setProperty('--accent',M.theme);document.title=M.title+' | SYSTEM ERROR';$('#title').textContent=M.title;$('#help').textContent=M.help;$('#back').href=q.get('test')==='1'?'index.html?test=1#select':'index.html#select';
const art=new Image(),artGroup=M.art.startsWith('world')?M.art.replace('world','w'):M.art;art.src=`chars-${artGroup}-${member}.webp`;art.onerror=()=>{art.onerror=null;art.src=`${member}.webp`};
const bg=new Image();bg.src=M.bg;
const rand=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const S={t:0,score:0,lives:3,done:false,won:false,pause:false,player:{x:80,y:500,vx:0,vy:0,ground:false},items:[],enemies:[],platforms:[],blocks:[],snake:[],dir:{x:1,y:0},nextDir:{x:1,y:0},timer:0,cam:0,worldX:0,fire:0,aim:0,dropX:480,cats:[],balls:[],keysFound:0};
const down=e=>{const k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys.add(k);if(k==='r')reset();if(k==='escape')S.pause=!S.pause;if(k===' '||k==='arrowup'||k==='w')jump();if(k===' '||k==='e'||k==='enter')action();if(id==='snake-grid'){if(k==='arrowup'||k==='w')turn(0,-1);if(k==='arrowdown'||k==='s')turn(0,1);if(k==='arrowleft'||k==='a')turn(-1,0);if(k==='arrowright'||k==='d')turn(1,0)}};
addEventListener('keydown',down);addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));$('#restart').onclick=reset;
document.querySelectorAll('.touch button').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();const k=b.dataset.k;keys.add(k);if(k==='jump'||k==='action')action();if(id==='snake-grid'){turn(k==='left'?-1:k==='right'?1:0,k==='jump'?-1:k==='action'?1:0)}};for(const ev of ['pointerup','pointercancel','pointerleave'])b.addEventListener(ev,()=>keys.delete(b.dataset.k))});
C.addEventListener('pointerdown',e=>{if(id==='ball-block'){const r=C.getBoundingClientRect(),x=(e.clientX-r.left)*W/r.width,y=(e.clientY-r.top)*H/r.height;S.aim=clamp(Math.atan2(y-560,x-480),-2.8,-.35);shoot()}else if(id==='cat-drop'){const r=C.getBoundingClientRect();S.dropX=clamp((e.clientX-r.left)*W/r.width,80,880);dropCat()}});
function turn(x,y){if(x===-S.dir.x&&y===-S.dir.y)return;S.nextDir={x,y}}
function reset(){Object.assign(S,{t:0,score:0,lives:3,done:false,won:false,pause:false,timer:0,cam:0,worldX:0,fire:0,aim:-Math.PI/2,dropX:480,keysFound:0,lastHit:-10});S.player={x:80,y:500,vx:0,vy:0,ground:false};S.items=[];S.enemies=[];S.platforms=[];S.blocks=[];S.snake=[];S.cats=[];S.balls=[];S.dir={x:1,y:0};S.nextDir={x:1,y:0};setup();}
function setup(){
 if(id==='pac-maze'||id==='ate-maze')setupMaze();
 if(id==='mario-platform'||id==='hop-run'){for(let i=0;i<28;i++){const x=180+i*118+(i%4===2?35:0);S.platforms.push({x,y:455-(i%5===0?90:0),w:82,h:18,kind:i%5===0?'high':'floor'});if(i%2===0)S.items.push({x:x+30,y:S.platforms.at(-1).y-35,kind:'spark',got:false});if(i%4===3)S.enemies.push({x:x+45,y:S.platforms.at(-1).y-35,w:24,h:28,vx:-45,hp:1})}S.player.x=80;S.player.y=420}
 if(id==='snake-grid'){S.snake=[{x:9,y:8},{x:8,y:8},{x:7,y:8}];putFood()}
 if(id==='cheese-dreams'){for(let i=0;i<11;i++){S.platforms.push({x:(i%2?650:210),y:530-i*54,w:160,h:18,move:i%2?1:-1})}for(let i=0;i<6;i++)S.items.push({x:rand(220,740),y:450-i*80,kind:'cheese',got:false});S.player={x:470,y:430,vx:0,vy:-80,ground:false}}
 if(id==='dino-run'){S.player={x:150,y:474,vx:0,vy:0,ground:true};S.nextObstacle=1.6}
 if(id==='ball-block'){S.blocks=[];newBlockRow()}
 if(id==='cat-drop')S.currentCat=0;
}
function setupMaze(){const map=id==='pac-maze'?[
'####################','P....#......#......E','#.##.#.####.#.##.#..','#....#....#...#.....','####.###.#.###.###.#','#......#.#.....#...#','#.####.#.#####.#.###','#......#...#...#....','###.######.#.######.','#...#......#........','#.#.#.########.###..','#...#..........#....','####################'
]:[
'####################','P....#.....#.......E','#.##.#.###.#.###.##.#','#....#...#...#......#','###.###.#.#####.###.#','#...#...#.....#...#.#','#.#.#.#####.#.###.#.#','#.#...#...#.#...#...#','#.#####.#.#.###.###.#','#.....#.#...#.....#.#','###.#.#.#####.###.#.#','#...#...#.....#...K.#','####################'];
if(id==='ate-maze')for(const [x,y] of [[2,1],[9,1]])map[y]=map[y].slice(0,x)+'K'+map[y].slice(x+1);
S.map=map;S.tile=30;S.mx=120;S.my=90;for(let y=0;y<map.length;y++)for(let x=0;x<map[y].length;x++){const v=map[y][x];if(v==='.'||v==='K')S.items.push({x,y,kind:v==='K'?'key':'dot',got:false});if(v==='E')S.exit={x,y};}S.mazePlayer={x:1,y:1,dx:0,dy:0,moveAt:0};S.mazeEnemies=[{x:17,y:1,dx:-1,dy:0,at:0},{x:16,y:10,dx:0,dy:-1,at:0}];}
function putFood(){let p;do{p={x:Math.floor(rand(1,29)),y:Math.floor(rand(1,17))}}while(S.snake.some(s=>s.x===p.x&&s.y===p.y));S.food=p}
function jump(){if(['mario-platform','hop-run','dino-run'].includes(id)&&S.player.ground){S.player.vy=-570;S.player.ground=false}}
function action(){if(S.done)return;if(id==='cat-drop')dropCat();else if(id==='ball-block')shoot();else if(id==='mario-platform'||id==='hop-run'||id==='dino-run')jump()}
function shoot(){if(S.done)return;S.balls.push({x:480,y:555,vx:Math.cos(S.aim)*560,vy:Math.sin(S.aim)*560,r:9});S.fire++;if(S.fire%5===0)newBlockRow()}
function newBlockRow(){for(let x=180;x<=780;x+=100)if(Math.random()<.62)S.blocks.push({x,y:140,n:Math.ceil(rand(2,5)),w:64,h:54});}
function dropCat(){if(id!=='cat-drop'||S.done)return;const level=S.currentCat||0;S.cats.push({x:S.dropX,y:55,r:22+level*4,level,vy:0});S.currentCat=Math.floor(rand(0,3));}
function collide(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function update(dt){if(S.done||S.pause)return;S.t+=dt;S.timer+=dt;const p=S.player,left=keys.has('a')||keys.has('arrowleft')||keys.has('left'),right=keys.has('d')||keys.has('arrowright')||keys.has('right'),up=keys.has('w')||keys.has('arrowup'),down=keys.has('s')||keys.has('arrowdown');
 if(id==='pac-maze'||id==='ate-maze')updateMaze(dt,up,down,left,right);
 if(id==='mario-platform'||id==='hop-run')updatePlatform(dt,p,left,right,up);
 if(id==='snake-grid'&&S.timer>.12){S.timer=0;snakeStep()}
 if(id==='cheese-dreams')updateCheese(dt,p,left,right);
 if(id==='dino-run')updateDino(dt,p);
 if(id==='ball-block')updateBlocks(dt);
 if(id==='cat-drop')updateCats(dt);
 if(!S.done&&S.lives<=0)finish(false);
 $('#score').textContent=(id==='snake-grid'?S.snake.length-3:S.score)+(id==='ate-maze'?` · KEYS ${S.keysFound}/3`:'');$('#clock').textContent=S.pause?'PAUSED':(['dino-run'].includes(id)?`${Math.ceil(Math.max(0,35-S.t))}s`:`♥ ${'◆'.repeat(Math.max(0,S.lives))}`);
}
function updateMaze(dt,up,down,left,right){const P=S.mazePlayer;if(S.t-P.moveAt>.105){P.moveAt=S.t;const dirs=[[0,-1,up],[0,1,down],[-1,0,left],[1,0,right]];for(const [dx,dy,pressed] of dirs)if(pressed&&!wall(P.x+dx,P.y+dy)){P.dx=dx;P.dy=dy;break}if(!wall(P.x+P.dx,P.y+P.dy)){P.x+=P.dx;P.y+=P.dy}for(const it of S.items)if(!it.got&&it.x===P.x&&it.y===P.y){it.got=true;S.score++;if(it.kind==='key')S.keysFound++}for(const e of S.mazeEnemies){if(S.t-e.at>.25){e.at=S.t;if(Math.random()<.75){const opts=[[1,0],[-1,0],[0,1],[0,-1]].filter(([x,y])=>!wall(e.x+x,e.y+y));if(opts.length){const d=opts[Math.floor(rand(0,opts.length))];e.dx=d[0];e.dy=d[1]}}e.x+=e.dx;e.y+=e.dy}}if(S.mazeEnemies.some(e=>e.x===P.x&&e.y===P.y)){S.lives--;P.x=1;P.y=1}if(P.x===S.exit.x&&P.y===S.exit.y){if(id==='pac-maze'&&!S.items.some(i=>!i.got&&i.kind==='dot'))finish(true);if(id==='ate-maze'&&S.keysFound>=3)finish(true)}}}
function wall(x,y){return !S.map?.[y]||S.map[y][x]==='#'}
function updatePlatform(dt,p,left,right,up){const speed=id==='hop-run'?270:300;p.vx=(right-left)*speed;if(up&&p.ground)jump();p.vy+=1500*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;S.worldX=Math.max(0,p.x-250);let floor=530;p.ground=false;for(const pl of S.platforms){const oldY=p.y-p.vy*dt;if(p.vy>=0&&p.x+26>pl.x&&p.x<pl.x+pl.w&&oldY+36<=pl.y&&p.y+36>=pl.y){p.y=pl.y-36;p.vy=0;p.ground=true;floor=Math.min(floor,pl.y)}}if(p.y+36>floor){p.y=floor-36;p.vy=0;p.ground=true}p.x=clamp(p.x,10,3000);for(const it of S.items)if(!it.got&&Math.abs((it.x-p.x))<28&&Math.abs(it.y-p.y)<40){it.got=true;S.score++}for(const e of S.enemies)if(e.hp&&collide({x:p.x,y:p.y,w:26,h:36},{x:e.x,y:e.y,w:e.w,h:e.h})){if(p.vy>70){e.hp=0;p.vy=-330;S.score++}else if(S.t-S.lastHit>1){S.lastHit=S.t;S.lives--;p.vx=-160;p.vy=-250}}if(id==='mario-platform'&&p.x>2900&&S.score>=8)finish(true);if(id==='hop-run'&&p.x>2900&&S.score>=7)finish(true)}
function updateCheese(dt,p,left,right){p.vx+=(right-left)*440*dt;p.vx*=.985;const oldY=p.y;p.vy+=940*dt;p.x=clamp(p.x+p.vx*dt,35,900);p.y+=p.vy*dt;for(const pl of S.platforms){pl.x+=pl.move*42*dt;if(pl.x<100||pl.x+pl.w>860)pl.move*=-1;if(p.vy>0&&p.x+26>pl.x&&p.x<pl.x+pl.w&&oldY+30<=pl.y&&p.y+30>=pl.y){p.y=pl.y-30;p.vy=-560;p.ground=true}}for(const it of S.items)if(!it.got&&Math.abs(p.x-it.x)<28&&Math.abs(p.y-it.y)<30){it.got=true;S.score++}if(p.y>570){p.y=570;p.vy=-580}if(S.score>=6)finish(true)}
function updateDino(dt,p){p.vy+=1500*dt;p.y+=p.vy*dt;if(p.y>=474){p.y=474;p.vy=0;p.ground=true}S.nextObstacle-=dt;if(S.nextObstacle<=0){S.enemies.push({x:1000,y:466,w:28+rand(0,32),h:38,vx:-420-S.t*5,hp:1});S.nextObstacle=rand(.8,1.45)}for(const e of S.enemies){e.x+=e.vx*dt;if(e.x<-60){e.hp=0;S.score++}if(e.hp&&collide({x:145,y:p.y,w:36,h:40},e)){if(p.vy>80){e.hp=0;p.vy=-430;p.ground=false;S.score++}else if(S.t-S.lastHit>1){S.lastHit=S.t;S.lives--}}}S.enemies=S.enemies.filter(e=>e.hp);if(S.t>=35&&S.score>=8)finish(true)}
function snakeStep(){if(!S.snake.length)return;S.dir=S.nextDir;const h={x:S.snake[0].x+S.dir.x,y:S.snake[0].y+S.dir.y};if(h.x<0||h.x>=30||h.y<0||h.y>=18||S.snake.some(s=>s.x===h.x&&s.y===h.y)){S.lives=0;return}S.snake.unshift(h);if(h.x===S.food.x&&h.y===S.food.y){S.score++;putFood();if(S.score>=8)finish(true)}else S.snake.pop()}
function updateBlocks(dt){for(const b of S.blocks){b.y+=12*dt;if(b.y+b.h>545)S.lives=0}for(const ball of S.balls){ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;if(ball.x<12||ball.x>948)ball.vx*=-1;for(const b of S.blocks)if(b.n>0&&ball.x>b.x&&ball.x<b.x+b.w&&ball.y>b.y&&ball.y<b.y+b.h){b.n--;ball.y=ball.vy<0?b.y+b.h+ball.r:b.y-ball.r;ball.vy*=-1;if(b.n<=0)S.score++;break}}S.blocks=S.blocks.filter(b=>b.n>0);S.balls=S.balls.filter(b=>b.y>-20&&b.y<610);if(S.score>=12)finish(true)}
function updateCats(dt){const movingLeft=keys.has('a')||keys.has('arrowleft')||keys.has('left'),movingRight=keys.has('d')||keys.has('arrowright')||keys.has('right');S.dropX=clamp(S.dropX+(movingRight-movingLeft)*320*dt,100,860);for(const a of S.cats){a.vy+=620*dt;a.y+=a.vy*dt;if(a.y+a.r>540){a.y=540-a.r;a.vy*=-.22;if(Math.abs(a.vy)<18)a.vy=0}}for(let i=0;i<S.cats.length;i++)for(let j=i+1;j<S.cats.length;j++){const a=S.cats[i],b=S.cats[j],d=Math.hypot(a.x-b.x,a.y-b.y);if(d<a.r+b.r&&a.level===b.level){a.level++;a.r+=5;a.x=(a.x+b.x)/2;a.y=Math.min(a.y,b.y);a.vy=-170;S.cats.splice(j,1);S.score++;if(a.level>=4)finish(true);break}else if(d<a.r+b.r&&d>0){const overlap=(a.r+b.r-d)/2;a.x+=(a.x-b.x)/d*overlap;a.y+=(a.y-b.y)/d*overlap;b.x-=(a.x-b.x)/d*overlap;b.y-=(a.y-b.y)/d*overlap}}if(S.cats.some(a=>a.y-a.r<30)&&S.t>8)S.lives=0}
function finish(win){if(S.done)return;S.done=true;S.won=win;$('#clock').textContent=win?'CLEARED!':'SIGNAL LOST';$('#help').textContent=win?'MISSION CLEAR · Press R to replay or return to the hub.':'MISSION FAILED · Press R to try again.';if(win){try{const a=JSON.parse(localStorage.getItem('skz.campaign.cleared')||'[]'),s=new Set(Array.isArray(a)?a:Object.keys(a).filter(k=>a[k]));s.add(missionId);localStorage.setItem('skz.campaign.cleared',JSON.stringify([...s]))}catch{}}}
function draw(){c.clearRect(0,0,W,H);if(bg.complete&&bg.naturalWidth){c.drawImage(bg,0,0,W,H);c.fillStyle='#061126aa';c.fillRect(0,0,W,H)}else{c.fillStyle='#101a39';c.fillRect(0,0,W,H)}
 if(id==='pac-maze'||id==='ate-maze')drawMaze();else if(id==='mario-platform'||id==='hop-run')drawPlatform();else if(id==='snake-grid')drawSnake();else if(id==='cheese-dreams')drawCheese();else if(id==='dino-run')drawDino();else if(id==='ball-block')drawBlocks();else if(id==='cat-drop')drawCats();
 c.fillStyle='#fff';c.font='18px monospace';c.fillText(M.title,20,30);if(S.pause){c.fillStyle='#031020bb';c.fillRect(0,0,W,H);c.fillStyle='#fff';c.font='32px monospace';c.fillText('PAUSED',420,300)}if(S.done){c.fillStyle='#031020c9';c.fillRect(0,0,W,H);c.strokeStyle=M.theme;c.lineWidth=3;c.strokeRect(285,220,390,155);c.fillStyle=M.theme;c.font='30px monospace';c.textAlign='center';c.fillText(S.won?'STAGE CLEAR':'TRY AGAIN',480,280);c.fillStyle='#fff';c.font='18px monospace';c.fillText('Press R to replay',480,325);c.textAlign='left'}}
function drawMaze(){const t=S.tile,map=S.map,P=S.mazePlayer;for(let y=0;y<map.length;y++)for(let x=0;x<map[y].length;x++){const xx=S.mx+x*t,yy=S.my+y*t;if(map[y][x]==='#'){c.fillStyle=id==='ate-maze'?'#233449':'#102b61';c.fillRect(xx,yy,t,t);c.strokeStyle=M.theme;c.strokeRect(xx+1,yy+1,t-2,t-2)}else{c.fillStyle='#07152d';c.fillRect(xx,yy,t,t);if(id==='ate-maze'&&map[y][x]==='E'){c.fillStyle=S.keysFound>=3?'#3dffd1':'#c64959';c.fillRect(xx+5,yy+3,20,25)}}}for(const it of S.items)if(!it.got){c.fillStyle=it.kind==='key'?'#ffe36b':M.theme;c.beginPath();c.arc(S.mx+it.x*t+15,S.my+it.y*t+15,it.kind==='key'?7:3,0,Math.PI*2);c.fill()}for(const e of S.mazeEnemies){c.fillStyle='#ff557e';c.beginPath();c.arc(S.mx+e.x*t+15,S.my+e.y*t+15,11,0,Math.PI*2);c.fill();c.fillStyle='#fff';c.fillRect(S.mx+e.x*t+9,S.my+e.y*t+8,4,4);c.fillRect(S.mx+e.x*t+18,S.my+e.y*t+8,4,4)}drawAvatar(S.mx+P.x*t+15,S.my+P.y*t+15,26,30)}
function drawAvatar(x,y,w,h){if(art.complete&&art.naturalWidth)c.drawImage(art,x-w/2,y-h/2,w,h);else{c.fillStyle=M.theme;c.fillRect(x-w/2,y-h/2,w,h)}}
function drawPlatform(){const cam=S.worldX;c.fillStyle='#111b30';c.fillRect(0,530,W,70);for(const p of S.platforms){const x=p.x-cam;if(x<-120||x>W+40)continue;c.fillStyle=id==='hop-run'?'#699fbe':'#59729c';c.fillRect(x,p.y,p.w,p.h);c.fillStyle='#d8f8ff';c.fillRect(x,p.y,p.w,4)}for(const it of S.items)if(!it.got){c.fillStyle=M.theme;c.beginPath();c.arc(it.x-cam,it.y,10,0,7);c.fill()}for(const e of S.enemies)if(e.hp){c.fillStyle='#c95c7d';c.fillRect(e.x-cam,e.y,e.w,e.h)}if(id==='hop-run'){c.fillStyle='#4ff';c.fillRect(850-(cam%960),0,8,525);c.fillRect(900-(cam%960),0,8,525)}drawAvatar(S.player.x-cam+14,S.player.y+18,30,38);c.fillStyle='#fff';c.fillText(`SPARKS ${S.score}/`+(id==='hop-run'?7:8),24,64)}
function drawSnake(){const t=27,ox=75,oy=75;c.fillStyle='#07152d';c.fillRect(ox,oy,810,486);c.strokeStyle='#244066';for(let x=0;x<=30;x++){c.beginPath();c.moveTo(ox+x*t,oy);c.lineTo(ox+x*t,oy+18*t);c.stroke()}for(let y=0;y<=18;y++){c.beginPath();c.moveTo(ox,oy+y*t);c.lineTo(ox+30*t,oy+y*t);c.stroke()}S.snake.forEach((s,i)=>{c.fillStyle=i?'#39d47f':'#b4ff74';c.fillRect(ox+s.x*t+2,oy+s.y*t+2,t-4,t-4)});if(S.food){c.fillStyle='#ff5d90';c.beginPath();c.arc(ox+S.food.x*t+13,oy+S.food.y*t+13,8,0,7);c.fill()}c.fillStyle='#fff';c.fillText(`ENERGY CELLS ${S.score}/8`,24,64)}
function drawCheese(){for(const p of S.platforms){c.fillStyle='#b777ff';c.fillRect(p.x,p.y,p.w,p.h);c.fillStyle='#ffeaff';c.fillRect(p.x,p.y,p.w,4)}for(const it of S.items)if(!it.got){c.fillStyle='#ffd34f';c.beginPath();c.moveTo(it.x-12,it.y-10);c.lineTo(it.x+12,it.y-10);c.lineTo(it.x+8,it.y+12);c.lineTo(it.x-9,it.y+12);c.closePath();c.fill();c.fillStyle='#fff1a0';c.fillRect(it.x-5,it.y-5,4,4)}drawAvatar(S.player.x,S.player.y,34,38);c.fillStyle='#fff';c.fillText(`MOON CHEESE ${S.score}/6`,24,64)}
function drawDino(){c.fillStyle='#f2f4e7';c.fillRect(0,510,W,3);for(let i=0;i<5;i++){const x=(i*230-S.t*180)%W;c.fillStyle='#c8d7d2';c.fillRect(x,90+(i%3)*30,35,2)}for(const e of S.enemies){c.fillStyle='#678778';c.fillRect(e.x,510-e.h,e.w,e.h);c.fillRect(e.x+8,480-e.h,7,16)}drawAvatar(164,S.player.y+20,42,44);c.fillStyle='#fff';c.fillText(`OBSTACLES ${S.score}/8`,24,64)}
function drawBlocks(){c.fillStyle='#0c1931';c.fillRect(100,90,760,430);for(const b of S.blocks){c.fillStyle='#38b6d5';c.fillRect(b.x,b.y,b.w,b.h);c.strokeStyle='#c7f5ff';c.strokeRect(b.x,b.y,b.w,b.h);c.fillStyle='#061326';c.font='20px monospace';c.fillText(b.n,b.x+27,b.y+34)}for(const b of S.balls){c.fillStyle=M.theme;c.beginPath();c.arc(b.x,b.y,b.r,0,7);c.fill()}c.fillStyle='#fff';c.fillRect(452,555,56,12);c.strokeStyle=M.theme;c.beginPath();c.moveTo(480,555);c.lineTo(480+Math.cos(S.aim)*70,555+Math.sin(S.aim)*70);c.stroke();c.fillText(`BLOCKS CLEARED ${S.score}/12`,24,64)}
function drawCats(){c.fillStyle='#674631';c.fillRect(80,538,800,10);c.strokeStyle='#d4a976';c.strokeRect(80,70,800,478);for(const a of S.cats){const cols=['#ff8fb8','#b292ff','#6ed9df','#ffd05c','#79db91'];c.fillStyle=cols[a.level%cols.length];c.beginPath();c.arc(a.x,a.y,a.r,0,7);c.fill();c.beginPath();c.moveTo(a.x-a.r*.6,a.y-a.r*.45);c.lineTo(a.x-a.r*.85,a.y-a.r*1.2);c.lineTo(a.x-a.r*.15,a.y-a.r*.7);c.fill();c.beginPath();c.moveTo(a.x+a.r*.6,a.y-a.r*.45);c.lineTo(a.x+a.r*.85,a.y-a.r*1.2);c.lineTo(a.x+a.r*.15,a.y-a.r*.7);c.fill();c.fillStyle='#293049';c.fillRect(a.x-a.r*.35,a.y-2,4,4);c.fillRect(a.x+a.r*.2,a.y-2,4,4);c.fillStyle='#fff';c.font='12px monospace';c.fillText(''+(a.level+1),a.x-4,a.y+14)}c.setLineDash([8,8]);c.strokeStyle='#ffffff77';c.beginPath();c.moveTo(S.dropX,40);c.lineTo(S.dropX,530);c.stroke();c.setLineDash([]);c.fillStyle='#fff';c.fillText('DROP ZONE · MERGE TO LEVEL 4',24,64)}
function loop(){const now=performance.now(),dt=Math.min(.033,((now-(S.last||now))/1000));S.last=now;update(dt);draw();requestAnimationFrame(loop)}
$('#mode-label').textContent=M.title;setup();requestAnimationFrame(loop);
})();
